### ISSUE TITLE
Best way of calling RTE+RRTMGP from a GCM

### ISSUE THREAD

**Issue by MHBalsmeier** [earth-system-radiation/rte-rrtmgp#93]
Hi,

this is a probably very silly question:
What is the best way of calling RTE+RRTMGP from a GCM?
Say, I have dry air density and temperature in all the grid boxes and I want to get back the spectrally integrated spectral flux density convergences as W/m^3.
Do I have to write out the atmospheric state as a netcdf file, then call RTE+RRTMGP and then get back a netcdf file with the radiation fluxes?
Should I compile the source code of RTE+RRTMGP into the GCM executable and then write an interface? Or should I compile RTE+RRTMGP separately and then use the files librrtmgp.a and librte.a?
I could not find information on this.

Thanks
Max

**Comment by RobertPincus** [comment]
If one were using RTE+RRTMGP to compute fluxes as part of the evolution of a GCM or other model one would certainly want to call the code from within the model rather than writing and reading lots of files. 

An example from the US Department of Energy's Energy Exascale Earth System Model is visible at https://github.com/E3SM-Project/E3SM/blob/master/components/eam/src/physics/rrtmgp/radiation.F90. This highlights how much infrastructure is involved in large models.

There's no functional difference between pre-compiling libraries and including the RTE+RRTMGP source code as part of building the model.

**Comment by MHBalsmeier** [comment]
Thanks, great.
